<?php

include_once('links/manifest.inc');
include_once('forms/manifest.inc');
include_once('sql/manifest.inc');

include_once("project");
include_once("project.list");

include_once("task");
include_once("task.list");

include_once("activity");
include_once("activity.list");

include_once("material");
include_once("material.list");

include_once("measure");
include_once("measure.list");

include_once("receipt");
include_once("receipt.list");

?>
