<?php
include_once ('_appEntitiesAlias.class');

include_once("_entityInterfaces.class");
include_once("_summary.class");
include_once("baseEntity.class");

include_once("entityLinks.class");
include_once("entitySQL.class");
include_once("entity.class");
include_once("entityList.class");

include_once("entityTypeLinks.class");
include_once("entityTypeSQL.class");
include_once("entityType.class");
include_once("entityTypeList.class");


include_once('./system/manifest.inc);
include_once('./reference/manifest.inc);
include_once('./projects/manifest.inc);
//include_once('./crops/manifest.inc);
//include_once('./courses/manifest.inc);

?>
