<?php
include_once('parameters/manifest.inc');
include_once('links/manifest.inc');
include_once('sql/manifest.inc');
include_once('forms/manifest.inc');


include_once("Ientity.class");
include_once("baseEntity.class");
include_once("entity.class");
include_once("entityList.class");
include_once("entityType.class");
include_once("entityTypeList.class");
include_once("systemMenu.class");

include_once('system/manifest.inc');
include_once('public/manifest.inc');
include_once('entities/manifest.inc');


?>
