<?php



include_once('parameters/manifest.inc');
include_once('links/manifest.inc');
include_once('sql/manifest.inc');
include_once('forms/manifest.inc');


include_once("Ientity");
include_once("base.entity");
include_once("entity");
include_once("entity.list");
include_once("entity.type");
include_once("entity.type.list");
include_once("system.menu");
include_once("mail.user.php");

include_once('system/manifest.inc');
include_once('public/manifest.inc');
include_once('entities/manifest.inc');

include_once('portal.request');

?>
