<?php
include_once('__inputTraits.class.php');

include_once('__input.class.php');
include_once('__button.class.php');

include_once('_select.class.php');

include_once('submit.class.php');
include_once('reset.class.php');

include_once('_selectOption.class.php');
include_once('selectRange.class.php');
include_once('selectQuery.class.php');
include_once('selectTimestamp.class.php');
include_once('selectColor.class.php');
include_once('selectFontFamily.class.php');
include_once('selectFontSize.class.php');
include_once('selectHighlight.class.php');
include_once('selectYesNo.class.php');



include_once('__inputCaptioned.class.php');

include_once('text.class.php');
include_once('textarea.class.php');
include_once('number.class.php');
include_once('timestamp.class.php');

include_once('hidden.class.php');
include_once('password.class.php');

include_once('email.class.php');


//based on inputTextarea
include_once('comments.class.php');
include_once('description.class.php');
include_once('notes.class.php');

//based on inputText
include_once('name.class.php');
include_once('user.class.php');
include_once('url.class.php');

?>
