<?php

include_once('links/manifest.inc');
include_once('forms/manifest.inc');

include_once ('_calendar.class');
include_once("_entityInterfaces.class");
include_once("_site.class");

include_once("baseEntity.class");

include_once("entityFields.class");
include_once("entitySQL.class");
include_once("entity.class");
include_once("entityList.class");

include_once("entityTypeFields.class");
include_once("entityTypeSQL.class");
include_once("entityType.class");
include_once("entityTypeList.class");


include_once('system/manifest.inc');
include_once('public/manifest.inc');

include_once('entities/reference/manifest.inc');
include_once('entities/projects/manifest.inc');

//include_once('entities/crops/manifest.inc');
//include_once('entities/courses/manifest.inc');

?>
