<?php

include_once("_calendar.class");
include_once ("_site.class");

include_once("publicSite.class");
include_once("publicSiteLinks.class");
include_once("publicSiteSQL.class");

include_once("userLogin.class");

include_once("systemMenu.class");
include_once("systemMenuLinks.class");

include_once('./entities/manifest.inc);
include_once('./forms/manifest.inc);
include_once('./parameters/manifest.inc);

?>
