<?php
include_once("project.fields");
include_once("task.fields");

include_once("activity.fields");
include_once("material.fields");
include_once("measure.fields");
include_once("receipt.fields");

include_once("base.summary");
include_once("base.cost.summary");
include_once("base.effort.summary");

include_once("receipt.summary");
include_once("material.summary");
include_once("project.summary");
include_once("task.summary");

?>
