<?php
include_once("pr_Project_Classes.php");
include_once("pr_ProjectType_Classes.php");
include_once("pr_Task_Classes.php");
include_once("pr_TaskType_Classes.php");
include_once("pr_Material_Classes.php");
include_once("pr_MaterialType_Classes.php");
include_once("pr_Receipt_Classes.php");
include_once("pr_ReceiptType_Classes.php");
include_once("pr_Activity_Classes.php");
include_once("pr_ActivityType_Classes.php");
include_once("pr_Location_Classes.php");
include_once("pr_LocationType_Classes.php");
include_once("pr_Measure_Classes.php");
include_once("pr_MeasureType_Classes.php");
include_once("pr_MeasureTypeUnit_Classes.php");
include_once("pr_UnitOfMeasure_Classes.php");
?>