<?php
include_once('__inputTraits.class');


include_once('_select.class');
include_once('_selectOption.class');
include_once('selectRange.class');
include_once('selectQuery.class');
include_once('selectTimestamp.class');
include_once('selectColor.class');
include_once('selectFontFamily.class');
include_once('selectFontSize.class');
include_once('selectHighlight.class');
include_once('selectYesNo.class');


include_once('__input.class');
include_once('__button.class');
include_once('__inputCaptioned.class');

include_once('_inputText.class');
include_once('_inputTextarea.class');
include_once('_inputNumber.class');
include_once('_inputTimestamp.class');

include_once('hidden.class');
include_once('password.class');
include_once('submit.class');
include_once('reset.class');



//based on inputTextarea
include_once('comments.class');
include_once('description.class');
include_once('notes.class');

//based on inputText
include_once('name.class');
include_once('user.class');
include_once('url.class');

?>
